### ISSUE TITLE
Toggle eco during cleaning

### ISSUE THREAD

**Issue by mkremeyer** [nicoh88/node-kobold#1]
I couldn't find a way to toggle the eco mode while the robot is in cleaning mode. Is that right? It's possible to do that via remote control, so I was wondering if this can also be achieved via API...?

PS: Amazing work. Thanks for providing this node module. I just started tinkering with my Kobold and I love it!

**Comment by mkremeyer** [comment]
For more context: I experimented with robot.eco. It's false by default, no matter if the robot is in eco mode or not. I can also change it, but this doesn't have an impact on the robot's eco mode.

**Comment by nicoh88** [comment]
Hello Marius, that's right. There is no chance to change cleaning mode during cleaning over the API at the moment.

Unfortunately there is no public vorwerk api documentation, therefore "[node-botvac](https://github.com/naofireblade/node-botvac)" and "[node-kobold](https://github.com/nicoh88/node-kobold)" ware based on the [public neato api documentation](https://developers.neatorobotics.com/api/robot-remote-protocol). According to the neato api documentation this is unfortunately not possible.

I'm no good coder. I copied only "[node-botvac](https://github.com/naofireblade/node-botvac)" from the main developer [Arne](https://github.com/naofireblade/) and changed the URL to Vorwerk - basically is it the same api. At best you must ask again Arne -  he had most of the work.
